/*
Feedback: 
nicely written :)
*/

// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int countSmall = 0;
		int countBig = 0;
		for (int i = 0; i<N; i++) {
			if (Math.random()< 0.5) {countSmall++;}
				else{
					countBig++;
				}  
		
	}
	
		double ratio = (double) countSmall/countBig;
		System.out.println ("> 0.5: " + countSmall + " times" );
		System.out.println ("<= 0.5: " + countBig + " times" );
		if (countBig != 0) { System.out.println ("Ratio: " + ratio);
	}


	}
}

